# -*- coding: utf-8 -*-
"""numpy project2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13SRKAxrH1XduJbDr49-iCM8ynLwqs5iB
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

from google.colab import files

uploaded = files.upload()

image_path = "bird.jpg"

image = mpimg.imread(image_path)

if image.max() <= 1.0:
    image = image * 255

image = image.astype(np.uint8)

print("===================================")
print("ORIGINAL IMAGE DETAILS")
print("===================================")

print(f"Image Shape : {image.shape}")
print(f"Data Type   : {image.dtype}")

grayscale = np.dot(
    image[:, :, :3],
    [0.2989, 0.5870, 0.1140]
)
grayscale = grayscale.astype(np.uint8)

print("\n===================================")
print("GRAYSCALE IMAGE DETAILS")
print("===================================")

print(f"Grayscale Shape : {grayscale.shape}")

bright_image = grayscale + 50
dark_image = grayscale - 50
bright_image = np.clip(bright_image, 0, 255)
dark_image = np.clip(dark_image, 0, 255)
bright_image = bright_image.astype(np.uint8)
dark_image = dark_image.astype(np.uint8)

rotated_image = np.rot90(grayscale)

height, width = grayscale.shape
cropped_image = grayscale[
    height // 4 : 3 * height // 4,
    width  // 4 : 3 * width  // 4
]

blurred_image = grayscale.copy()
for i in range(1, grayscale.shape[0] - 1):
    for j in range(1, grayscale.shape[1] - 1):

        blurred_image[i, j] = np.mean(
            grayscale[i-1:i+2, j-1:j+2]
        )
blurred_image = blurred_image.astype(np.uint8)

fig, axes = plt.subplots(2, 5, figsize=(22, 10))


plt.suptitle(
    "Grayscale Image Manipulator Project",
    fontsize=20,
    fontweight="bold"
)


axes[0, 0].imshow(image)
axes[0, 0].set_title("Original Image")
axes[0, 0].axis("off")


axes[0, 1].imshow(grayscale, cmap="gray")
axes[0, 1].set_title("Grayscale")
axes[0, 1].axis("off")


axes[0, 2].imshow(bright_image, cmap="gray")
axes[0, 2].set_title("Brightened Image")
axes[0, 2].axis("off")


axes[0, 3].imshow(dark_image, cmap="gray")
axes[0, 3].set_title("Darkened Image")
axes[0, 3].axis("off")

rotated_image = np.rot90(grayscale)
axes[0, 4].imshow(rotated_image, cmap="gray")
axes[0, 4].set_title("Rotated Image")
axes[0, 4].axis("off")

horizontal_flip = np.fliplr(grayscale)
axes[1, 0].imshow(horizontal_flip, cmap="gray")
axes[1, 0].set_title("Horizontal Flip")
axes[1, 0].axis("off")

vertical_flip = np.flipud(grayscale)
axes[1, 1].imshow(vertical_flip, cmap="gray")
axes[1, 1].set_title("Vertical Flip")
axes[1, 1].axis("off")


axes[1, 2].imshow(cropped_image, cmap="gray")
axes[1, 2].set_title("Cropped Image")
axes[1, 2].axis("off")


axes[1, 3].imshow(blurred_image, cmap="gray")
axes[1, 3].set_title("Blurred Image")
axes[1, 3].axis("off")


axes[1, 4].hist(
    grayscale.ravel(),
    bins=50
)

axes[1, 4].set_title("Pixel Intensity Histogram")
axes[1, 4].set_xlabel("Pixel Value")
axes[1, 4].set_ylabel("Frequency")

plt.tight_layout()
plt.show()

print("\n===================================")
print("PROJECT COMPLETED SUCCESSFULLY")
print("===================================")