# -*- coding: utf-8 -*-
"""numpy project1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BA_cw4zzZR4EMlWTqHNVnEcPB-wqWi3u
"""

import numpy as np
np.random.seed(42)
scores = np.random.randint(0, 101, size=50)

print("===================================")
print("STUDENT SCORES")
print("===================================")
print(scores)

mean_score = np.mean(scores)
median_score = np.median(scores)
highest_score = np.max(scores)
lowest_score = np.min(scores)
standard_deviation = np.std(scores)

print("\n===================================")
print("BASIC STATISTICS")
print("===================================")

print(f"Mean Score           : {mean_score:.2f}")
print(f"Median Score         : {median_score}")
print(f"Highest Score        : {highest_score}")
print(f"Lowest Score         : {lowest_score}")
print(f"Standard Deviation   : {standard_deviation:.2f}")

percentile_25 = np.percentile(scores, 25)
percentile_50 = np.percentile(scores, 50)
percentile_90 = np.percentile(scores, 90)

print("\n===================================")
print("PERCENTILE ANALYSIS")
print("===================================")

print(f"25th Percentile : {percentile_25}")
print(f"50th Percentile : {percentile_50}")
print(f"90th Percentile : {percentile_90}")

failed_students_indices = np.where(scores < 40)[0]
distinction_students_indices = np.where(scores > 85)[0]

print("\n===================================")
print("FAILED STUDENTS (Score < 40)")
print("===================================")

for idx in failed_students_indices:
    print(f"Student {idx + 1}: Score = {scores[idx]}")

print("\n===================================")
print("DISTINCTION STUDENTS (Score > 85)")
print("===================================")

for idx in distinction_students_indices:
    print(f"Student {idx + 1}: Score = {scores[idx]}")

reshaped_scores = scores.reshape(5, 10)

print("\n===================================")
print("RESHAPED SCORE MATRIX (5 x 10)")
print("===================================")

print(reshaped_scores)

row_wise_average = np.mean(reshaped_scores, axis=1)

print("\n===================================")
print("SUBJECT-WISE AVERAGES")
print("===================================")

for i, avg in enumerate(row_wise_average, start=1):
    print(f"Subject {i} Average Score = {avg:.2f}")

theory_scores = np.random.randint(0, 101, size=50)
practical_scores = np.random.randint(0, 101, size=50)


weighted_final_scores = (
    (0.4 * theory_scores) + (0.6 * practical_scores)
)

print("\n===================================")
print("THEORY SCORES")
print("===================================")

print(theory_scores)

print("\n===================================")
print("PRACTICAL SCORES")
print("===================================")

print(practical_scores)

print("\n===================================")
print("WEIGHTED FINAL SCORES")
print("===================================")

print(weighted_final_scores)

print("\n===================================")
print("GRADE ASSIGNMENT")
print("===================================")

for i, score in enumerate(weighted_final_scores, start=1):

    if score >= 90:
        grade = 'A+'
    elif score >= 80:
        grade = 'A'
    elif score >= 70:
        grade = 'B'
    elif score >= 60:
        grade = 'C'
    elif score >= 40:
        grade = 'D'
    else:
        grade = 'F'

    print(f"Student {i}: Final Score = {score:.2f} | Grade = {grade}")

print("\n===================================")
print("PROJECT COMPLETED SUCCESSFULLY")
print("===================================")